// <auto-generated />
using System;
using AsyncInn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsyncInn.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    [Migration("20190420232703_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsyncInn.Models.Amenities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("RoomsID");

                    b.HasKey("ID");

                    b.HasIndex("RoomsID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Balcony"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Minibar"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Ocean View"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Disco Ball"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Water Bed"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.HotelRooms", b =>
                {
                    b.Property<int>("HotelsID");

                    b.Property<int>("RoomsID");

                    b.Property<bool>("PetFriendly");

                    b.Property<int>("Rate");

                    b.Property<int>("RoomNumber");

                    b.HasKey("HotelsID", "RoomsID");

                    b.HasIndex("RoomsID");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("AsyncInn.Models.Hotels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Seattle",
                            Name = "Hotel Cartmon",
                            Phone = "206-956-5555",
                            State = "Washington",
                            StreetAddress = "123 E 8th St"
                        },
                        new
                        {
                            ID = 2,
                            City = "Seattle",
                            Name = "Hotel Code Fellows",
                            Phone = "206-654-5555",
                            State = "Washington",
                            StreetAddress = "123 E 8th St"
                        },
                        new
                        {
                            ID = 3,
                            City = "Seattle",
                            Name = "Hotel Red",
                            Phone = "206-648-5555",
                            State = "Washington",
                            StreetAddress = "44 S 8th St"
                        },
                        new
                        {
                            ID = 4,
                            City = "Seattle",
                            Name = "Hotel Cartmon",
                            Phone = "206-956-5555",
                            State = "Washington",
                            StreetAddress = "954 W 7th St"
                        },
                        new
                        {
                            ID = 5,
                            City = "Seattle",
                            Name = "Hotel Bebop",
                            Phone = "360-956-1235",
                            State = "Washington",
                            StreetAddress = "888 E 89th St"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.RoomAmenities", b =>
                {
                    b.Property<int>("RoomsID");

                    b.Property<int>("AmenitiesID");

                    b.HasKey("RoomsID", "AmenitiesID");

                    b.HasIndex("AmenitiesID");

                    b.ToTable("RoomAmenities");
                });

            modelBuilder.Entity("AsyncInn.Models.Rooms", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Name = "Studio"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 1,
                            Name = "One Bedroom"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 2,
                            Name = "Two Bedroom"
                        },
                        new
                        {
                            ID = 4,
                            Layout = 3,
                            Name = "Penthouse"
                        },
                        new
                        {
                            ID = 5,
                            Layout = 4,
                            Name = "Queen Suite"
                        },
                        new
                        {
                            ID = 6,
                            Layout = 5,
                            Name = "King Suite"
                        });
                });

            modelBuilder.Entity("AsyncInn.Models.Amenities", b =>
                {
                    b.HasOne("AsyncInn.Models.Rooms")
                        .WithMany("Amenities")
                        .HasForeignKey("RoomsID");
                });

            modelBuilder.Entity("AsyncInn.Models.HotelRooms", b =>
                {
                    b.HasOne("AsyncInn.Models.Hotels", "Hotels")
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AsyncInn.Models.Rooms", "Rooms")
                        .WithMany("HotelRooms")
                        .HasForeignKey("RoomsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AsyncInn.Models.RoomAmenities", b =>
                {
                    b.HasOne("AsyncInn.Models.Amenities", "Amenities")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenitiesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AsyncInn.Models.Rooms", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
